spring:
  datasource:
   url: jdbc:mysql://localhost:3306/goods?useUnicode=true&characterEncoding=UTF-8&useSSL=false
   username: root
   password: 13201230
   driver-class-name: com.mysql.cj.jdbc.Driver
